### ISSUE TITLE
Evaluar ajustes

### ISSUE THREAD

**Issue by eliansoutu** [dnme-minturdep/mapeAr#2]
- [x] agregar como capa predefinida la de capitales
- [x] Para la capa "rutas naturales" es posible que si seleccionamos una provincia se vea solo las rutas que pasan por esa provincia 
- [ ] que se pueda filtrar por ruta y definir por ej si filtro una ruta que el resto se vean en gris

**Comment by jpruiznicolini** [comment]
Incorporar {waiter}  @eliansoutu  ?

**Comment by eliansoutu** [comment]
Se incorporaron los ajustes
